### ISSUE TITLE
NoSuchNodeTypeException

### ISSUE THREAD

**Issue by StupidSmart** [apache/sling-org-apache-sling-starter#304]
Hey, I have 3 files which I use to start my sling12 server -
1.sling12-kickstart.jar
2.custom-feature.json
3.custom-script
Now, when I start the server everything works fine, but when I go to the bin browser to try and create a node with primary type -
vlt:PackageDefinition
It gives me -
Error - 400 javax.jcr.nodetype.NoSuchNodeTypeException: Node type vlt:PackageDefinition does not exist
But when I go to the packages section in the bin browser and come back to create a node with the same type it is successful.
First of all I don't understand the behaviour of this and how do I fix this as I want that node type on startup?
The composum node version in my feature.json is 4.2.3!

**Comment by rombert** [comment]
Hi @StupidSmart and thanks for your report.

Please use the users mailing list ( https://sling.apache.org/project-information.html#mailing-lists-1 ) for support queries. 

There seems to be a very similar post at https://lists.apache.org/thread/kmxc48soggf3vpnwo9prm10zs9so1b6n, perhaps you can join the conversation there?
